In [1]:
import numpy as np
import json_tricks

In [ ]:

def qr_iteration(A):

    
    return lambdas, misfits
    





[1. 1. 2.]
[ 1.  3. -1.]
[0. 1. 1.]
[[ 0.40824829  0.20739034 -0.88900089]
 [ 0.40824829  0.82956136  0.38100038]
 [ 0.81649658 -0.51847585  0.25400025]]


In [ ]:
from tqdm import tqdm

inputs = json_tricks.load('inputs.json')

results = []
for args in tqdm(inputs):
    res = qr_iteration(**args)
    results.append(res)

json_tricks.dump(results, '.answer.json')

In [ ]:
import matplotlib.pyplot as plt

for res in results[:10]:
    misfits = res[1]
    plt.plot(np.array(misfits))

