In [1]:
import numpy as np
import json_tricks

In [13]:
def qr_iteration(A):

    n = A.shape[0]
    
    
    def get_Q(A):
        
        Q = np.zeros_like(A, dtype=float)
        
        for i in range(A.shape[1]):
            
            # i-th coliumn of A
            q = A[:, i]

            for j in range(i):
                # subtract the projection of q onto the j-th column of Q from q
                q -= np.dot(Q[:, j], A[:, i]) * Q[:, j]

            # normalize the vector q
            Q[:, i] = q / np.linalg.norm(q)
            
        return Q

    def get_R(A):
        return np.triu(A)


    # do the QR decomposition
    Q = get_Q(A)
    R = get_R(np.dot(Q.T, A))

    A = np.dot(R, Q)
    
    
    return lambdas, misfits
    
test = np.array([[3.0, 1.0], [2.0, 2.0]])
test2 = np.array([[1.0, 1.0, 0.0], [1.0, 3.0, 1.0], [2.0, -1.0, 1.0]])

qr_iteration(test2)




[1. 1. 2.]
[ 1.  3. -1.]
[0. 1. 1.]
[[ 0.40824829  0.20739034 -0.88900089]
 [ 0.40824829  0.82956136  0.38100038]
 [ 0.81649658 -0.51847585  0.25400025]]


In [ ]:
from tqdm import tqdm

inputs = json_tricks.load('inputs.json')

results = []
for args in tqdm(inputs):
    res = qr_iteration(**args)
    results.append(res)

json_tricks.dump(results, '.answer.json')

In [ ]:
import matplotlib.pyplot as plt

for res in results[:10]:
    misfits = res[1]
    plt.plot(np.array(misfits))

