In [113]:
import numpy as np
import json_tricks
from pathlib import Path
import os

In [114]:

from itertools import permutations

def determinant(A):
    # Ensure the matrix is square
    n = A.shape[0]
    assert A.shape[0] == A.shape[1]
    
    print(len(A))

    det = 0
    elements = []

    ### YOUR CODE HERE ###

    print(A)
    
    for el in permutations(A):
        print(el)
    
    print("\n-----------------\n")

    n = len(A)
    det = 0
    elements = []
    
    for perm in permutations(range(n)):
        product = 1
        inversions = 0
        
        for i in range(n):
            product *= A[i][perm[i]] # here we multiply the elements of the matrix by the permutation

            print(f"Matrix element: {A[i]}")
            print(f"Permutation element: {perm[i]}")
            
            for j in range(i + 1, n):
                if perm[i] > perm[j]:
                    inversions += 1
    
        
        if inversions % 2:
            sign = -1
        else:
            sign = 1
        
        contribution = sign * product
        det += contribution
        elements.append((perm, sign, product, contribution))

    

    return det, sorted(elements)


In [115]:
inputs = json_tricks.load('inputs.json')
results = {'results': []}

for args in inputs['inputs']:
    results['results'].append([determinant(**args)])

json_tricks.dump(results, '.answer.json')

4
[[-10   3   9   3]
 [ -8   3 -10  -9]
 [  7   6   2   1]
 [  3   2   6   7]]
(array([-10,   3,   9,   3]), array([ -8,   3, -10,  -9]), array([7, 6, 2, 1]), array([3, 2, 6, 7]))
(array([-10,   3,   9,   3]), array([ -8,   3, -10,  -9]), array([3, 2, 6, 7]), array([7, 6, 2, 1]))
(array([-10,   3,   9,   3]), array([7, 6, 2, 1]), array([ -8,   3, -10,  -9]), array([3, 2, 6, 7]))
(array([-10,   3,   9,   3]), array([7, 6, 2, 1]), array([3, 2, 6, 7]), array([ -8,   3, -10,  -9]))
(array([-10,   3,   9,   3]), array([3, 2, 6, 7]), array([ -8,   3, -10,  -9]), array([7, 6, 2, 1]))
(array([-10,   3,   9,   3]), array([3, 2, 6, 7]), array([7, 6, 2, 1]), array([ -8,   3, -10,  -9]))
(array([ -8,   3, -10,  -9]), array([-10,   3,   9,   3]), array([7, 6, 2, 1]), array([3, 2, 6, 7]))
(array([ -8,   3, -10,  -9]), array([-10,   3,   9,   3]), array([3, 2, 6, 7]), array([7, 6, 2, 1]))
(array([ -8,   3, -10,  -9]), array([7, 6, 2, 1]), array([-10,   3,   9,   3]), array([3, 2, 6, 7]))
(array([ -8,

'{"results": [[[-4402, [[[0, 1, 2, 3], 1, -420, -420], [[0, 1, 3, 2], -1, -180, 180], [[0, 2, 1, 3], -1, 4200, -4200], [[0, 2, 3, 1], 1, 200, 200], [[0, 3, 1, 2], 1, 3240, 3240], [[0, 3, 2, 1], -1, 360, -360], [[1, 0, 2, 3], -1, -336, 336], [[1, 0, 3, 2], 1, -144, -144], [[1, 2, 0, 3], 1, -1470, -1470], [[1, 2, 3, 0], -1, -90, 90], [[1, 3, 0, 2], -1, -1134, 1134], [[1, 3, 2, 0], 1, -162, -162], [[2, 0, 1, 3], 1, -3024, -3024], [[2, 0, 3, 1], -1, -144, 144], [[2, 1, 0, 3], -1, 1323, -1323], [[2, 1, 3, 0], 1, 81, 81], [[2, 3, 0, 1], 1, -1134, -1134], [[2, 3, 1, 0], -1, -1458, 1458], [[3, 0, 1, 2], -1, -864, 864], [[3, 0, 2, 1], 1, -96, -96], [[3, 1, 0, 2], 1, 378, 378], [[3, 1, 2, 0], -1, 54, -54], [[3, 2, 0, 1], -1, -420, 420], [[3, 2, 1, 0], 1, -540, -540]]]], [[-84, [[[0, 1, 2], 1, -80, -80], [[0, 2, 1], -1, -40, 40], [[1, 0, 2], -1, 0, 0], [[1, 2, 0], 1, 0, 0], [[2, 0, 1], 1, -4, -4], [[2, 1, 0], -1, 40, -40]]]], [[-1098, [[[0, 1, 2], 1, -336, -336], [[0, 2, 1], -1, 384, -384], [[1, 